# Generated by Django 5.2.11 on 2026-03-08 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic_storage', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='genericinstance',
            new_name='generic_sto_dm_ct_i_cdac95_idx',
            old_name='generic_sto_dm_ct_i_8a3b9e_idx',
        ),
        migrations.RenameIndex(
            model_name='genericinstance',
            new_name='generic_sto_validat_fda382_idx',
            old_name='generic_sto_validat_2e8f5c_idx',
        ),
        migrations.RenameIndex(
            model_name='genericinstance',
            new_name='generic_sto_rdf_syn_47042a_idx',
            old_name='generic_sto_rdf_syn_6c7d4a_idx',
        ),
        migrations.RenameIndex(
            model_name='genericinstance',
            new_name='generic_sto_json_in_54523d_gin',
            old_name='generic_sto_json_in_9f8e7b_gin',
        ),
        migrations.AddField(
            model_name='genericinstance',
            name='source_instance_id',
            field=models.CharField(blank=True, default='', help_text='Identifier from the originating source system', max_length=255),
        ),
        migrations.AddField(
            model_name='genericinstance',
            name='source_version_id',
            field=models.CharField(blank=True, default='', help_text='Version identifier from the originating source system', max_length=255),
        ),
    ]
