#!/usr/bin/env python3
"""
Generate the year of orders, responses, dispatch advices, receipt advices and invoices for both stacks.

The retailer, Kestrel Mercantile, is the system of record for its purchase orders: each order is
generated as a record of the published Order model and loaded into the retailer's stack. On the way
out of that stack every record is written as a UBL 2.3 Order document into
``app/sdc4/import_data/exchange/``. On the way in to the supplier's stack, Halvorsen Foods, each
document is read back into a record by the translator: the supplier's record names the document it
came from as the PROV entity the activity used, the translator as the agent, and the document as the
audit's location. Two stacks, one component set, the document a projection between them.

    python datagen/generate_all.py            # HALVORSEN_ORDERS=52 by default: a year of weekly orders
    HALVORSEN_ORDERS=260 python datagen/generate_all.py

Then the supplier answers: each response is generated as a record in the supplier's stack, written as a UBL 2.3
OrderResponse into the exchange, and read back into the retailer's stack by the retailer's translator. Then the
supplier ships: each dispatch advice is generated by the warehouse system as a record in the supplier's stack,
written as a UBL 2.3 DespatchAdvice into the exchange, and read back into the retailer's stack the same way. Then the retailer
receives: each receipt advice is generated by the receiving system as a record in the retailer's stack, every unit checked on the
receipt date, written as a UBL 2.3 ReceiptAdvice into the exchange, and read back into the supplier's stack by the supplier's translator. Then the supplier
bills: each invoice is generated by the billing system for what the receipt says arrived, written as a UBL 2.3 Invoice into the exchange,
and read back into the retailer's stack by the retailer's translator.

Writes app/sdc4/import_data/{retailer,halvorsen}/{order,order_response,dispatch_advice}/ and app/sdc4/import_data/exchange/.
Every UBL document is validated against the OASIS schema of its type before it is written.
"""
from __future__ import annotations

import glob
import os
import sys
import time

sys.path.insert(0, os.path.dirname(__file__))
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "ubl"))
from dispatch_advice import read_dispatch_advice, validate_ubl_dispatch, write_dispatch_advice  # noqa: E402
from halvorsen import generate  # noqa: E402
from halvorsen_dispatch import dispatch  # noqa: E402
from halvorsen_invoices import invoice  # noqa: E402
from halvorsen_receipts import receive  # noqa: E402
from halvorsen_responses import respond  # noqa: E402
from invoice import read_invoice, validate_ubl_invoice, write_invoice  # noqa: E402
from order import read_order, validate_ubl, write_order  # noqa: E402
from order_response import read_order_response, validate_ubl_response, write_order_response  # noqa: E402
from receipt_advice import read_receipt_advice, validate_ubl_receipt, write_receipt_advice  # noqa: E402
from shared import IMPORT_ROOT, RETAILER_TRANSLATOR, SUPPLIER_TRANSLATOR, record, write_record  # noqa: E402

ORDERS = int(os.environ.get("HALVORSEN_ORDERS", "52"))
SEED = os.environ.get("HALVORSEN_SEED", "halvorsen-2026")


def exchange(directory: str, name: str, ubl: str) -> str:
    """A validated document written into the exchange and read back from disk, the way the other side receives it."""
    path = os.path.join(directory, f"{name}.xml")
    with open(path, "w", encoding="utf-8") as f:
        f.write('<?xml version="1.0" encoding="UTF-8"?>\n' + ubl)
    with open(path, encoding="utf-8") as f:
        return f.read()


def main():
    import random
    t0 = time.time()
    dirs = {name: os.path.join(IMPORT_ROOT, *parts) for name, parts in {
        "retailer_orders": ("retailer", "order"), "supplier_orders": ("halvorsen", "order"),
        "supplier_responses": ("halvorsen", "order_response"), "retailer_responses": ("retailer", "order_response"),
        "supplier_dispatches": ("halvorsen", "despatch_advice"), "retailer_dispatches": ("retailer", "despatch_advice"),
        "retailer_receipts": ("retailer", "receipt_advice"), "supplier_receipts": ("halvorsen", "receipt_advice"),
        "supplier_invoices": ("halvorsen", "invoice"), "retailer_invoices": ("retailer", "invoice"), "exchange": ("exchange",)}.items()}
    for d in dirs.values():
        os.makedirs(d, exist_ok=True)
        for f in glob.glob(os.path.join(d, "*.xml")):
            os.remove(f)
    print("=" * 60)
    print(f"HalvorsenDemo generator: {ORDERS} orders, their responses, dispatch advices, receipt advices and invoices, seed {SEED!r}")
    print("=" * 60)
    rng = random.Random(SEED + ":responses")
    drng = random.Random(SEED + ":dispatches")
    krng = random.Random(SEED + ":receipts")
    irng = random.Random(SEED + ":invoices")
    n = 0; lapsed = 0; stale = 0; problems = 0; deposits = 0
    for h, values, xml in generate(ORDERS, seed=SEED):
        # 1. the retailer's order, the system of record; written out as a UBL Order; read in by the supplier
        write_record(dirs["retailer_orders"], "order", xml, name=h["order_id"].lower())
        ubl = write_order(xml)
        assert not validate_ubl(ubl), (h["order_id"], validate_ubl(ubl)[:2])
        received = read_order(exchange(dirs["exchange"], h["order_id"], ubl))
        supplier_order = record("Order", received, document_id=h["order_id"], buyer=h["buyer"], when=f"{h['issued']}T{h['received_time']}",
                                source=(f"urn:kestrel:order:{h['order_id']}:ubl", f"{h['order_id']}.xml", "The UBL 2.3 Order received from Kestrel Mercantile"),
                                agent=SUPPLIER_TRANSLATOR, current_state="OrderProcessing")
        write_record(dirs["supplier_orders"], "order", supplier_order, name=h["order_id"].lower())
        # 2. the supplier's response, its system of record; written out as a UBL OrderResponse; read in by the retailer
        rh, rvalues, rxml = respond(h, values, rng)
        write_record(dirs["supplier_responses"], "order_response", rxml, name=rh["response_id"].lower())
        rubl = write_order_response(rxml)
        assert not validate_ubl_response(rubl), (rh["response_id"], validate_ubl_response(rubl)[:2])
        rreceived = read_order_response(exchange(dirs["exchange"], rh["response_id"], rubl))
        retailer_response = record("Order Response", rreceived, document_id=rh["response_id"], buyer=rh["seller"], when=f"{rh['issued']}T{rng.randint(9, 17):02d}:{rng.randint(0, 59):02d}:00",
                                   source=(f"urn:halvorsen:response:{rh['response_id']}:ubl", f"{rh['response_id']}.xml", "The UBL 2.3 OrderResponse received from Halvorsen Foods"),
                                   agent=RETAILER_TRANSLATOR, current_state="OrderProcessing")
        write_record(dirs["retailer_responses"], "order_response", retailer_response, name=rh["response_id"].lower())
        # 3. the supplier's dispatch advice, from its warehouse system; written out as a UBL DespatchAdvice; read in by the retailer
        dh, dvalues, dxml = dispatch(h, values, rh, rvalues, drng)
        write_record(dirs["supplier_dispatches"], "despatch_advice", dxml, name=dh["dispatch_id"].lower())
        dubl = write_dispatch_advice(dxml)
        assert not validate_ubl_dispatch(dubl), (dh["dispatch_id"], validate_ubl_dispatch(dubl)[:2])
        dreceived = read_dispatch_advice(exchange(dirs["exchange"], dh["dispatch_id"], dubl))
        retailer_dispatch = record("Despatch Advice", dreceived, document_id=dh["dispatch_id"], buyer=dh["seller"], when=f"{dh['issued']}T{drng.randint(16, 21):02d}:{drng.randint(0, 59):02d}:00",
                                   source=(f"urn:halvorsen:dispatch:{dh['dispatch_id']}:ubl", f"{dh['dispatch_id']}.xml", "The UBL 2.3 DespatchAdvice received from Halvorsen Foods"),
                                   agent=RETAILER_TRANSLATOR, current_state="OrderInTransit")
        write_record(dirs["retailer_dispatches"], "despatch_advice", retailer_dispatch, name=dh["dispatch_id"].lower())
        # 4. the retailer's receipt advice, from its receiving system, every unit checked on the receipt date; written out as a UBL ReceiptAdvice; read in by the supplier
        kh, kvalues, kxml = receive(h, values, dh, dvalues, krng)
        write_record(dirs["retailer_receipts"], "receipt_advice", kxml, name=kh["receipt_id"].lower())
        kubl = write_receipt_advice(kxml)
        assert not validate_ubl_receipt(kubl), (kh["receipt_id"], validate_ubl_receipt(kubl)[:2])
        kreceived = read_receipt_advice(exchange(dirs["exchange"], kh["receipt_id"], kubl))
        supplier_receipt = record("Receipt Advice", kreceived, document_id=kh["receipt_id"], buyer=kh["buyer"], when=f"{kh['received']}T{krng.randint(17, 21):02d}:{krng.randint(0, 59):02d}:00",
                                  source=(f"urn:kestrel:receipt:{kh['receipt_id']}:ubl", f"{kh['receipt_id']}.xml", "The UBL 2.3 ReceiptAdvice received from Kestrel Mercantile"),
                                  agent=SUPPLIER_TRANSLATOR, current_state="OrderProblem" if kh["exceptions"] else "OrderDelivered")
        write_record(dirs["supplier_receipts"], "receipt_advice", supplier_receipt, name=kh["receipt_id"].lower())
        # 5. the supplier's invoice, from its billing system, for what the receipt says arrived; written out as a UBL Invoice; read in by the retailer
        ih, ivalues, ixml = invoice(h, values, rh, rvalues, dh, kh, kvalues, irng)
        write_record(dirs["supplier_invoices"], "invoice", ixml, name=ih["invoice_id"].lower())
        iubl = write_invoice(ixml)
        assert not validate_ubl_invoice(iubl), (ih["invoice_id"], validate_ubl_invoice(iubl)[:2])
        ireceived = read_invoice(exchange(dirs["exchange"], ih["invoice_id"], iubl))
        retailer_invoice = record("Invoice", ireceived, document_id=ih["invoice_id"], buyer=ih["seller"], when=f"{ih['issued']}T{irng.randint(17, 21):02d}:{irng.randint(0, 59):02d}:00",
                                  source=(f"urn:halvorsen:invoice:{ih['invoice_id']}:ubl", f"{ih['invoice_id']}.xml", "The UBL 2.3 Invoice received from Halvorsen Foods"),
                                  agent=RETAILER_TRANSLATOR, current_state="OrderPaymentDue")
        write_record(dirs["retailer_invoices"], "invoice", retailer_invoice, name=ih["invoice_id"].lower())
        lapsed += dh["pallet_lapses"]; stale += dh["pack_stale"]; problems += bool(kh["exceptions"]); deposits += ih["kind"] == "deposit"
        n += 1
    # 6. the settled records: for every Settlement Receipt issued on a receipt advice in OrderProblem (settlement/), the
    #    record in the state the settlement reached, its provenance naming the Receipt; only where the bytes still match
    sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "settlement"))
    from settled import write_settled_records  # noqa: E402
    settled, unmatched = write_settled_records(IMPORT_ROOT)
    for name, d in dirs.items():
        print(f"  {name:<20} {len(glob.glob(os.path.join(d, '*.xml'))):>6,}   {d}")
    print(f"  {n} orders; {lapsed} dispatches with a pallet identifier that lapses on the day of dispatch; {stale} packed to the replaced pack specification; {problems} receipts in OrderProblem; {deposits} invoices with a deposit deducted; {settled} settled records from the Receipts held ({unmatched} not matching)")
    print(f"Completed in {time.time() - t0:.1f}s")


if __name__ == "__main__":
    main()
