#!/usr/bin/env python3
"""
Generate the year of orders, responses and despatch advices for both stacks.

The retailer, Kestrel Mercantile, is the system of record for its purchase orders: each order is
generated as a record of the published Order model and loaded into the retailer's stack. On the way
out of that stack every record is written as a UBL 2.3 Order document into
``app/sdc4/import_data/exchange/``. On the way in to the supplier's stack, Halvorsen Foods, each
document is read back into a record by the translator: the supplier's record names the document it
came from as the PROV entity the activity used, the translator as the agent, and the document as the
audit's location. Two stacks, one component set, the document a projection between them.

    python datagen/generate_all.py            # HALVORSEN_ORDERS=52 by default: a year of weekly orders
    HALVORSEN_ORDERS=260 python datagen/generate_all.py

Then the supplier answers: each response is generated as a record in the supplier's stack, written as a UBL 2.3
OrderResponse into the exchange, and read back into the retailer's stack by the retailer's translator. Then the
supplier ships: each despatch advice is generated by the warehouse system as a record in the supplier's stack,
written as a UBL 2.3 DespatchAdvice into the exchange, and read back into the retailer's stack the same way.

Writes app/sdc4/import_data/{retailer,halvorsen}/{order,order_response,despatch_advice}/ and app/sdc4/import_data/exchange/.
Every UBL document is validated against the OASIS schema of its type before it is written.
"""
from __future__ import annotations

import glob
import os
import sys
import time

sys.path.insert(0, os.path.dirname(__file__))
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "ubl"))
from despatch_advice import read_despatch_advice, validate_ubl_despatch, write_despatch_advice  # noqa: E402
from halvorsen import generate  # noqa: E402
from halvorsen_despatch import despatch  # noqa: E402
from halvorsen_responses import respond  # noqa: E402
from order import read_order, validate_ubl, write_order  # noqa: E402
from order_response import read_order_response, validate_ubl_response, write_order_response  # noqa: E402
from shared import IMPORT_ROOT, RETAILER_TRANSLATOR, SUPPLIER_TRANSLATOR, record, write_record  # noqa: E402

ORDERS = int(os.environ.get("HALVORSEN_ORDERS", "52"))
SEED = os.environ.get("HALVORSEN_SEED", "halvorsen-2026")


def exchange(directory: str, name: str, ubl: str) -> str:
    """A validated document written into the exchange and read back from disk, the way the other side receives it."""
    path = os.path.join(directory, f"{name}.xml")
    with open(path, "w", encoding="utf-8") as f:
        f.write('<?xml version="1.0" encoding="UTF-8"?>\n' + ubl)
    with open(path, encoding="utf-8") as f:
        return f.read()


def main():
    import random
    t0 = time.time()
    dirs = {name: os.path.join(IMPORT_ROOT, *parts) for name, parts in {
        "retailer_orders": ("retailer", "order"), "supplier_orders": ("halvorsen", "order"),
        "supplier_responses": ("halvorsen", "order_response"), "retailer_responses": ("retailer", "order_response"),
        "supplier_despatches": ("halvorsen", "despatch_advice"), "retailer_despatches": ("retailer", "despatch_advice"), "exchange": ("exchange",)}.items()}
    for d in dirs.values():
        os.makedirs(d, exist_ok=True)
        for f in glob.glob(os.path.join(d, "*.xml")):
            os.remove(f)
    print("=" * 60)
    print(f"HalvorsenDemo generator: {ORDERS} orders, their responses and their despatch advices, seed {SEED!r}")
    print("=" * 60)
    rng = random.Random(SEED + ":responses")
    drng = random.Random(SEED + ":despatches")
    n = 0; lapsed = 0; stale = 0
    for h, values, xml in generate(ORDERS, seed=SEED):
        # 1. the retailer's order, the system of record; written out as a UBL Order; read in by the supplier
        write_record(dirs["retailer_orders"], "order", xml, name=h["order_id"].lower())
        ubl = write_order(xml)
        assert not validate_ubl(ubl), (h["order_id"], validate_ubl(ubl)[:2])
        received = read_order(exchange(dirs["exchange"], h["order_id"], ubl))
        supplier_order = record("Order", received, document_id=h["order_id"], buyer=h["buyer"], when=f"{h['issued']}T{h['received_time']}",
                                source=(f"urn:kestrel:order:{h['order_id']}:ubl", f"{h['order_id']}.xml", "The UBL 2.3 Order received from Kestrel Mercantile"),
                                agent=SUPPLIER_TRANSLATOR, current_state="OrderProcessing")
        write_record(dirs["supplier_orders"], "order", supplier_order, name=h["order_id"].lower())
        # 2. the supplier's response, its system of record; written out as a UBL OrderResponse; read in by the retailer
        rh, rvalues, rxml = respond(h, values, rng)
        write_record(dirs["supplier_responses"], "order_response", rxml, name=rh["response_id"].lower())
        rubl = write_order_response(rxml)
        assert not validate_ubl_response(rubl), (rh["response_id"], validate_ubl_response(rubl)[:2])
        rreceived = read_order_response(exchange(dirs["exchange"], rh["response_id"], rubl))
        retailer_response = record("Order Response", rreceived, document_id=rh["response_id"], buyer=rh["seller"], when=f"{rh['issued']}T{rng.randint(9, 17):02d}:{rng.randint(0, 59):02d}:00",
                                   source=(f"urn:halvorsen:response:{rh['response_id']}:ubl", f"{rh['response_id']}.xml", "The UBL 2.3 OrderResponse received from Halvorsen Foods"),
                                   agent=RETAILER_TRANSLATOR, current_state="OrderProcessing")
        write_record(dirs["retailer_responses"], "order_response", retailer_response, name=rh["response_id"].lower())
        # 3. the supplier's despatch advice, from its warehouse system; written out as a UBL DespatchAdvice; read in by the retailer
        dh, dvalues, dxml = despatch(h, values, rh, rvalues, drng)
        write_record(dirs["supplier_despatches"], "despatch_advice", dxml, name=dh["despatch_id"].lower())
        dubl = write_despatch_advice(dxml)
        assert not validate_ubl_despatch(dubl), (dh["despatch_id"], validate_ubl_despatch(dubl)[:2])
        dreceived = read_despatch_advice(exchange(dirs["exchange"], dh["despatch_id"], dubl))
        retailer_despatch = record("Despatch Advice", dreceived, document_id=dh["despatch_id"], buyer=dh["seller"], when=f"{dh['issued']}T{drng.randint(16, 21):02d}:{drng.randint(0, 59):02d}:00",
                                   source=(f"urn:halvorsen:despatch:{dh['despatch_id']}:ubl", f"{dh['despatch_id']}.xml", "The UBL 2.3 DespatchAdvice received from Halvorsen Foods"),
                                   agent=RETAILER_TRANSLATOR, current_state="OrderInTransit")
        write_record(dirs["retailer_despatches"], "despatch_advice", retailer_despatch, name=dh["despatch_id"].lower())
        lapsed += dh["pallet_lapses"]; stale += dh["pack_stale"]
        n += 1
    for name, d in dirs.items():
        print(f"  {name:<20} {len(glob.glob(os.path.join(d, '*.xml'))):>6,}   {d}")
    print(f"  {n} orders; {lapsed} despatches with a pallet identifier that lapses on the day of despatch; {stale} packed to the replaced pack specification")
    print(f"Completed in {time.time() - t0:.1f}s")


if __name__ == "__main__":
    main()
