"""
Django settings for sdc4 project.

Generated by SDCStudio AppGen (Enterprise Stack).
"""

import importlib
from pathlib import Path
from decouple import config, Csv
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# One source of truth for the version: app/sdc4/VERSION. Templates read it through
# sdc4.context_processors.app_version; the release workflow refuses a tag
# that does not match it.
APP_VERSION = (BASE_DIR / 'VERSION').read_text(encoding='utf-8').strip()


def _discover_local_apps():
    """Auto-discover installed DM apps by scanning for directories with apps.py."""
    from django.apps import AppConfig as _AppConfig
    _skip = {
        'api', 'core', 'demo', 'console', 'generic_storage', 'sdc4_shared',
        'templates', 'staticfiles', 'mediafiles', 'ontologies',
        Path(__file__).resolve().parent.name,  # project config package
    }
    discovered = []
    for entry in sorted(BASE_DIR.iterdir()):
        if not entry.is_dir() or entry.name in _skip:
            continue
        if entry.name.startswith('.') or entry.name.startswith('_'):
            continue
        if not (entry / 'apps.py').exists():
            continue
        try:
            mod = importlib.import_module(f'{entry.name}.apps')
            if any(
                isinstance(getattr(mod, attr, None), type)
                and issubclass(getattr(mod, attr), _AppConfig)
                and getattr(mod, attr) is not _AppConfig
                for attr in dir(mod)
            ):
                discovered.append(entry.name)
        except Exception:
            pass
    return discovered


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-sdc4-key')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

_allowed_hosts_str = config('ALLOWED_HOSTS', default='localhost,127.0.0.1')
_sep = ';' if ';' in _allowed_hosts_str else ','
ALLOWED_HOSTS = [h.strip() for h in _allowed_hosts_str.split(_sep) if h.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party apps
    'crispy_forms',
    'crispy_bootstrap5',
    'rest_framework',
    'django_htmx',
    'widget_tweaks',

    # Project apps
    'core',  # Management commands and utilities
    'generic_storage',  # File storage backend
    'api',  # REST API endpoints
    'demo',  # C-Suite demo presentation
    'console',  # Executive console: one record, three projections
] + _discover_local_apps()

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_htmx.middleware.HtmxMiddleware',
]

ROOT_URLCONF = 'sdc4.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'sdc4.context_processors.app_version',
            ],
        },
    },
]

WSGI_APPLICATION = 'sdc4.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=config('DATABASE_URL', default='sqlite:///db.sqlite3'),
        conn_max_age=600
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Third-party CSS and JS are vendored here rather than pulled from a CDN. This
# stack is meant to clone and run on a machine with no outbound network, and a
# demo that renders unstyled without one is not a demo.
STATICFILES_DIRS = [BASE_DIR / 'static']
STORAGES = {
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'mediafiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Crispy Forms
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# Celery Configuration
# https://docs.celeryproject.org/en/stable/django/first-steps-with-django.html

CELERY_BROKER_URL = config('CELERY_BROKER_URL', default='redis://localhost:6379/0')
CELERY_RESULT_BACKEND = config('CELERY_RESULT_BACKEND', default='redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutes
CELERY_TASK_SOFT_TIME_LIMIT = 25 * 60  # 25 minutes

# SPARQL Query Cache (in-process, no external dependencies)
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'sparql-cache',
        'TIMEOUT': 30,  # 30 seconds
        'OPTIONS': {
            'MAX_ENTRIES': 100,
        },
    },
}

# =============================================================================
# Enterprise Stack Configuration
# =============================================================================

# GraphDB Configuration (OWL 2 Reasoning Triplestore)
# Replaces Apache Fuseki in the lightweight stack
GRAPHDB_URL = config('GRAPHDB_URL', default='http://localhost:17200')
GRAPHDB_REPOSITORY = config('GRAPHDB_REPOSITORY', default='sdc4_rdf')
# Where a browser reaches GraphDB Workbench (the in-container GRAPHDB_URL is not
# browser-reachable). The demo's entity graph links every node to Workbench here.
GRAPHDB_WORKBENCH_URL = config('GRAPHDB_WORKBENCH_URL', default='http://localhost:17200')
GRAPHDB_USER = config('GRAPHDB_USER', default='admin')
GRAPHDB_PASSWORD = config('GRAPHDB_PASSWORD', default='admin123')

# Authentication
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# =============================================================================
# GCP / Production Configuration
# =============================================================================

# Trust X-Forwarded-Proto from Cloud Run load balancer
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# CSRF trusted origins (comma-separated in env)
_csrf_origins = config('CSRF_TRUSTED_ORIGINS', default='', cast=Csv())
CSRF_TRUSTED_ORIGINS = [o for o in _csrf_origins if o]
