# Generated by Django 5.2.17 on 2026-09-28 19:52

import order.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInstance',
            fields=[
                ('instance_id', models.CharField(default=order.models.generate_instance_id, help_text='Unique instance identifier. Format: i-{cuid} or i-ev-{cuid}', max_length=50, primary_key=True, serialize=False)),
                ('xml_content', models.TextField(help_text='Complete validated SDC4 XML instance - this is the authoritative data')),
                ('json_instance', models.JSONField(default=dict, help_text='Complete JSON representation of XML for JSONB queries')),
                ('search_text', models.TextField(blank=True, default='', help_text='Concatenated searchable text from all values for full-text search')),
                ('validation_status', models.CharField(choices=[('valid', 'Valid'), ('valid_with_ev', 'Valid with Exceptional Values'), ('invalid', 'Invalid')], db_index=True, default='valid', max_length=20)),
                ('validation_errors', models.JSONField(blank=True, default=dict, help_text='Validation errors encountered, if any')),
                ('auto_corrected_fields', models.JSONField(blank=True, default=list, help_text='List of field labels that were auto-corrected with Exceptional Values')),
                ('rdf_sync_status', models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced'), ('failed', 'Failed'), ('disabled', 'Disabled')], db_index=True, default='pending', max_length=20)),
                ('fuseki_graph_uri', models.URLField(blank=True, default='', help_text='URI of the named graph in the triplestore')),
                ('rdf_uploaded_at', models.DateTimeField(blank=True, help_text='Timestamp when RDF was last uploaded to triplestore', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Order Instance',
                'verbose_name_plural': 'Order Instances',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['validation_status', 'created_at'], name='order_order_validat_3b4082_idx'), models.Index(fields=['rdf_sync_status'], name='order_order_rdf_syn_117c00_idx')],
            },
        ),
    ]
