"""
Read helpers over the domain instance models.

Every DM app generated by SDCStudio AppGen stores the same shape: the validated
XML is authoritative, a clean JSON projection sits beside it for querying, and
the validation outcome is recorded on the row. The console renders those three
without transforming anything, which is the point it exists to make.
"""
import xml.etree.ElementTree as ET
from typing import Any, Dict, List, Optional

from sdc4_shared.utils.dm_registry import get_model_for_dm_ct_id
from sdc4_shared.utils.dm_title import dm_title

# ISO 21090 null flavors, as carried by SDC4 Exceptional Values. The element tag
# IS the code, so these are looked up by tag rather than by an xsi:type.
EV_NAMES = {
    'NI': 'No Information',
    'MSK': 'Masked',
    'INV': 'Invalid',
    'DER': 'Derived',
    'UNC': 'Unencoded',
    'OTH': 'Other',
    'NINF': 'Negative Infinity',
    'PINF': 'Positive Infinity',
    'ASKR': 'Asked and Refused',
    'NASK': 'Not Asked',
    'NAV': 'Not Available',
    'NA': 'Not Applicable',
    'TRC': 'Trace',
    'ASKU': 'Asked but Unknown',
    'UNK': 'Unknown',
    'QS': 'Sufficient Quantity',
}


def get_instance(ct_id: str, instance_id: str):
    """Resolve a DM CT_ID to its model class and fetch one instance, or None."""
    model = get_model_for_dm_ct_id(ct_id)
    if model is None:
        return None, None
    try:
        return model, model.objects.get(pk=instance_id)
    except model.DoesNotExist:
        return model, None


def _strip_ns(tag: str) -> str:
    return tag.split('}', 1)[1] if '}' in tag else tag


def component_ids_by_label(xml_content: str) -> Dict[str, str]:
    """
    Map a field label to the CT_ID of the component that governs it.

    Every value in an SDC4 instance sits inside an ``ms-{ct_id}`` element that
    carries its own ``label``. That element name is the identity of the sealed
    component, which is what the console's "governed by" column reports. The
    constraint detail behind it is read from the schema in a later step.
    """
    out: Dict[str, str] = {}
    try:
        root = ET.fromstring(xml_content)
    except ET.ParseError:
        return out

    for elem in root.iter():
        tag = _strip_ns(elem.tag)
        if not tag.startswith('ms-'):
            continue
        ct = tag[3:]
        for child in elem:
            if _strip_ns(child.tag) == 'label' and child.text:
                out.setdefault(child.text.strip(), ct)
                break
    return out


def field_rows(instance) -> List[Dict[str, Any]]:
    """
    Flatten ``json_instance['fields']`` into rows for the table projection.

    The JSON projection is generated from the same XML the document pane shows,
    so the two panes cannot disagree. An absent value carries an Exceptional
    Value code rather than a blank, and the row reports it as a stated absence.
    """
    payload = instance.json_instance or {}
    fields = payload.get('fields', {})
    components = component_ids_by_label(instance.xml_content or '')

    rows = []
    for label, data in fields.items():
        if not isinstance(data, dict):
            data = {'value': data}
        ev_code = data.get('ev')
        rows.append({
            'label': label,
            'value': data.get('value'),
            'units': data.get('units') or '',
            'ev_code': ev_code,
            'ev_name': EV_NAMES.get(ev_code, ev_code) if ev_code else '',
            'component': components.get(label, ''),
        })
    rows.sort(key=lambda r: r['label'])
    return rows


def stated_absences(instance) -> List[str]:
    """
    Field labels whose value is an Exceptional Value.

    Read from the record itself rather than from ``auto_corrected_fields``.
    That column records what the loader corrected on the way in, which is a
    different event from what the record states about itself, and a record
    authored with an Exceptional Value has nothing to correct.
    """
    fields = (instance.json_instance or {}).get('fields', {})
    return sorted(
        label for label, d in fields.items()
        if isinstance(d, dict) and d.get('ev')
    )


def neighbours(model, instance) -> Dict[str, Any]:
    """
    Where this record sits in its domain, and what is either side of it.

    Ordered newest first, with the primary key as a tiebreak, because a bulk
    load writes hundreds of rows inside the same second and an ordering that is
    not total will show the same record twice while skipping another.
    """
    ids = list(
        model.objects.order_by('-created_at', 'instance_id')
        .values_list('instance_id', flat=True)
    )
    try:
        i = ids.index(instance.instance_id)
    except ValueError:
        return {'position': None, 'total': len(ids), 'prev': None, 'next': None}
    return {
        'position': i + 1,
        'total': len(ids),
        'prev': ids[i - 1] if i > 0 else None,
        'next': ids[i + 1] if i + 1 < len(ids) else None,
    }


def instance_header(model, instance) -> Dict[str, Any]:
    """Identity and assurance facts shown above the projection switch."""
    absences = stated_absences(instance)
    return {
        'stated_absences': absences,
        'stated_absence_count': len(absences),
        'dm_label': dm_title(model),
        'ct_id': getattr(model, 'DM_CT_ID', ''),
        'instance_id': instance.instance_id,
        'validation_status': instance.validation_status,
        'validation_label': instance.get_validation_status_display(),
        'validation_errors': instance.validation_errors or {},
        'auto_corrected': instance.auto_corrected_fields or [],
        # The identifier itself records that this instance carries a stated
        # absence: AppGen rewrites the prefix to i-ev- rather than leaving the
        # fact only in a status column.
        'is_ev_instance': instance.instance_id.startswith('i-ev-'),
        'rdf_sync_status': instance.rdf_sync_status,
        'graph_uri': instance.fuseki_graph_uri,
        'created_at': instance.created_at,
        'app_label': model._meta.app_label,
    }
