"""
The console's question for this stack: where did every record come from, and what does it hold?

Each stack answers for itself. The retailer's records were generated by its order system; the
supplier's were read from the documents the retailer sent, and each names the document as the PROV
entity its activity used and the translator as the agent. The question counts the records by the
agent that produced them and lists the orders by month with their payable totals, every number
answered by the store from the reifiers of bound components, never from a mapping table.

Every component is bound by its ct_id (the reifier is addressed by its label and its component read
from its IRI): a triple term with the component unbound makes GraphDB scan every reifier.
"""
from __future__ import annotations

import time
from typing import Any, Dict

from django.core.cache import cache

from sdc4_shared.utils.dm_registry import get_dm_registry
from sdc4_shared.utils.graphdb_client import GraphDBClient

CACHE_SECONDS = 24 * 3600   # keyed by the record count, so a reload invalidates the answers

PREFIXES = """PREFIX sdc4: <https://semanticdatacharter.com/ns/sdc4/>
PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
"""
AGENT_NAME = "xxe21o9ojzmy9wxxky1tnmog"      # PROV Agent / Agent Name
ENTITY_LABEL = "m9minyaug6ypyzt52zfxlyyi"    # PROV Entity / Entity Label: the document the activity used
ORDER_ID = "wtnd4hzyrntlwtp4z3l1gcpr"         # Order Document / Order ID
ISSUE_DATE = "tkd16hhh9wbn0qya2ykm0552"       # Order Document / Issue Date
PAYABLE = "axifzu4nt8m8n4qpfn838yy8"          # Anticipated Monetary Total / Payable Amount

ORIGIN = PREFIXES + """
SELECT ?agent (COUNT(DISTINCT ?inst) AS ?records) (SAMPLE(?inst) AS ?sample) (SAMPLE(?dm) AS ?dmid) WHERE {
  ?a rdfs:label "Agent Name" ; sdc4:inInstance ?inst ; sdc4:inDataModel ?dm ; rdf:reifies <<sdc4:mc-%s ?ap ?agent>> .
}
GROUP BY ?agent
ORDER BY DESC(?records)
""" % AGENT_NAME

MONTHS = PREFIXES + """
SELECT ?month (COUNT(DISTINCT ?inst) AS ?orders) (SUM(xsd:decimal(?payable)) AS ?total) (SAMPLE(?inst) AS ?sample) (SAMPLE(?dm) AS ?dmid) WHERE {
  ?d rdfs:label "Issue Date" ; sdc4:inInstance ?inst ; sdc4:inDataModel ?dm ; rdf:reifies <<sdc4:mc-%s ?dp ?issued>> .
  ?p rdfs:label "Payable Amount" ; sdc4:inInstance ?inst ; rdf:reifies <<sdc4:mc-%s ?pp ?payable>> .
  FILTER(isLiteral(?payable) && REGEX(STR(?payable), "^[0-9.]+$"))
  BIND(SUBSTR(STR(?issued), 1, 7) AS ?month)
}
GROUP BY ?month
ORDER BY ?month
""" % (ISSUE_DATE, PAYABLE)

DOCUMENTS = PREFIXES + """
SELECT (COUNT(DISTINCT ?inst) AS ?records) (COUNT(DISTINCT ?doc) AS ?documents) WHERE {
  ?e rdfs:label "Entity Label" ; sdc4:inInstance ?inst ; rdf:reifies <<sdc4:mc-%s ?ep ?doc>> .
  FILTER(STRENDS(STR(?doc), ".xml"))
}
""" % ENTITY_LABEL


def _loaded() -> int:
    return sum(m.objects.count() for m in get_dm_registry().values())


def _rows(client, query):
    result = client.query_sparql(query)
    return (result or {}).get('results', {}).get('bindings', [])


def _v(binding, key, default=''):
    return binding.get(key, {}).get('value', default)


def _open(binding):
    inst, dm = _v(binding, 'sample'), _v(binding, 'dmid')
    if inst and dm:
        return {'ct_id': dm.rsplit('/dm-', 1)[-1], 'instance_id': inst.rsplit('/', 1)[-1]}
    return None


def origin() -> Dict[str, Any]:
    """Which system produced this stack's records, and how many name a document they were read from."""
    records = _loaded()
    key = f'console:origin:{records}'
    hit = cache.get(key)
    if hit:
        return hit
    client = GraphDBClient()
    t0 = time.time()
    try:
        rows = [{'agent': _v(b, 'agent'), 'records': int(_v(b, 'records', '0')), 'open': _open(b)} for b in _rows(client, ORIGIN)]
        docs = _rows(client, DOCUMENTS)
    except Exception as exc:   # the store being down leaves the page standing and saying why
        return {'unavailable': f'The triple store did not answer: {exc}', 'records': records}
    from_documents = int(_v(docs[0], 'documents', '0')) if docs else 0
    out = {'rows': rows, 'records': records, 'from_documents': from_documents, 'elapsed': round(time.time() - t0, 1), 'query': ORIGIN.strip()}
    cache.set(key, out, CACHE_SECONDS)
    return out


def months() -> Dict[str, Any]:
    """The orders by month of issue, with the payable total the records carry."""
    records = _loaded()
    key = f'console:months:{records}'
    hit = cache.get(key)
    if hit:
        return hit
    client = GraphDBClient()
    t0 = time.time()
    try:
        rows = [{'month': _v(b, 'month'), 'orders': int(_v(b, 'orders', '0')), 'total': _v(b, 'total'), 'open': _open(b)} for b in _rows(client, MONTHS)]
    except Exception as exc:
        return {'unavailable': f'The triple store did not answer: {exc}', 'records': records}
    out = {'rows': rows, 'orders': sum(r['orders'] for r in rows), 'elapsed': round(time.time() - t0, 1), 'query': MONTHS.strip()}
    cache.set(key, out, CACHE_SECONDS)
    return out
